export const REGISTERED_USER_FIRST_NAME = "REGISTERED_USER_FIRST_NAME";
export const REGISTERED_USER_LAST_NAME = "REGISTERED_USER_LAST_NAME";
export const REGISTERED_USER_DATE_OF_BIRTH = "REGISTERED_USER_DATE_OF_BIRTH";
export const REGISTERED_USER_GENDER = "REGISTERED_USER_GENDER";
export const REGISTERED_USER_COUNTRY_CODE = "REGISTERED_USER_COUNTRY_CODE";
export const REGISTERED_USER_PHONE_NUMBER = "REGISTERED_USER_PHONE_NUMBER";

export const ONBOARD_USER_REQUEST = "ONBOARD_USER_REQUEST";
export const ONBOARD_USER_SUCCESS = "ONBOARD_USER_SUCCESS";
export const ONBOARD_USER_FAILURE = "ONBOARD_USER_FAILURE";
