export const REGISTER_USER_EMAIL_ADDRESS = "REGISTER_USER_EMAIL_ADDRESS";
export const REGISTER_USER_PASSWORD = "REGISTER_USER_PASSWORD";
export const REGISTER_USER_CONFIRM_PASSWORD = "REGISTER_USER_CONFIRM_PASSWORD";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
