export const LOGIN_USER_EMAIL_ADDRESS = "LOGIN_USER_EMAIL_ADDRESS";
export const LOGIN_USER_PASSWORD = "LOGIN_USER_PASSWORD";
export const LOGIN_USER_REMEMBER_ME = "LOGIN_USER_REMEMBER_ME";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
