export const REGISTERED_USER_EMAIL_ADDRESS = "REGISTERED_USER_EMAIL_ADDRESS";
export const FORGOT_PASSWORD_GENERATE_OTP = "FORGOT_PASSWORD_GENERATE_OTP";
export const FORGOT_PASSWORD_NEW_PASSWORD = "FORGOT_PASSWORD_NEW_PASSWORD";
export const FORGOT_PASSWORD_CONFIRM_PASSWORD = "FORGOT_PASSWORD_CONFIRM_PASSWORD";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";